In [41]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression 
import numpy as np

In [20]:
from sklearn.datasets import load_digits

In [21]:
digits= load_digits()

In [22]:
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [23]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [25]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [26]:
from sklearn.model_selection import cross_val_score

In [51]:
lg =cross_val_score(LogisticRegression(
     penalty='l2',
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=550,
    multi_class='deprecated',
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
),digits.data,digits.target,cv=5)

In [52]:
lg

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [53]:
np.average(lg)

np.float64(0.9137650882079852)

In [38]:
svm =cross_val_score(SVC(),digits.data,digits.target,cv=5)

In [39]:
svm

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [40]:
np.average(svm)

np.float64(0.9632838130609718)

In [48]:
rf =cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=5)

In [49]:
rf

array([0.92777778, 0.90555556, 0.96100279, 0.9637883 , 0.9275766 ])

In [50]:
np.average(rf)

np.float64(0.9371402042711235)